### ISSUE TITLE
MergeBamAlignment -- Do not use this function to merge dictionaries with different sequences in them 

### ISSUE THREAD

**Issue by jurtlest** [broadinstitute/Drop-seq#212] opened 2020-09-30 15:27 UTC
Hi All, 

While I am running the dropseq pipeline following the protocol from version 2.0.0 (9/28/18), I have ran into a roadblock that I am unable to solve. I've seen multiple people having the same issue with MergeBamAlignment, but there really isn't a definitive solution for this. I'm wondering if anyone here has also experienced this problem and if you know how to correct this ??? 

I followed every step of the pipeline and have no problem until this step.
The input files for the MergeBamAlignment step are as follow:
UNMAPPED BAM = bam file after polyAtrimming before converted back to sam. 
ALIGNED_BAM = bam after STAR alignment and converted to SAM. 
REFERENCE = GRCm38.fa.gz  -- Mus musculus genome donwloaded from ncbi / Also used to create .dict and refFlat files earlier

I'm wondering if this could be due to what the files were STAR aligned to, causing the dictionary error ??? 

Thanks in advance!! 

Error message below: 

Exception in thread "main" java.lang.IllegalArgumentException: Do not use this function to merge dictionaries with different sequences in them. Sequences must be in the same order as well. Found [1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 3, 4, 5, 6, 7, 8, 9, MT, X, Y, JH584299.1, GL456233.1, JH584301.1, GL456211.1, GL456350.1, JH584293.1, GL456221.1, JH584297.1, JH584296.1, GL456354.1, JH584294.1, JH584298.1, JH584300.1, GL456219.1, GL456210.1, JH584303.1, JH584302.1, GL456212.1, JH584304.1, GL456379.1, GL456216.1, GL456393.1, GL456366.1, GL456367.1, GL456239.1, GL456213.1, GL456383.1, GL456385.1, GL456360.1, GL456378.1, GL456389.1, GL456372.1, GL456370.1, GL456381.1, GL456387.1, GL456390.1, GL456394.1, GL456392.1, GL456382.1, GL456359.1, GL456396.1, GL456368.1, JH584292.1, JH584295.1] and [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chrX, chrY, chrM, KZ289080.1, KZ289081.1, GL456210.1, GL456211.1, GL456212.1, GL456213.1, GL456216.1, GL456219.1, GL456221.1, GL456233.1, GL456239.1, GL456350.1, GL456354.1, GL456359.1, GL456360.1, GL456366.1, GL456367.1, GL456368.1, GL456370.1, GL456372.1, GL456378.1, GL456379.1, GL456381.1, GL456382.1, GL456383.1, GL456385.1, GL456387.1, GL456389.1, GL456390.1, GL456392.1, GL456393.1, GL456394.1, GL456396.1, JH584292.1, JH584293.1, JH584294.1, JH584295.1, JH584296.1, JH584297.1, JH584298.1, JH584299.1, JH584300.1, JH584301.1, JH584302.1, JH584303.1, JH584304.1, KZ289092.1, KQ030490.1, KB469738.3, JH792830.1, KV575237.1, KK082442.1, KV575240.1, KV575235.1, KZ289088.1, KV575239.1, KQ030495.1, KV575238.1, KZ289082.1, KV575234.1, KZ289072.1, KQ030485.1, KQ030486.1, KQ030487.1, KZ289070.1, KZ289084.1, KZ289085.1, KZ289093.1, KZ289094.1, KZ289095.1, KZ289090.1, KZ289091.1, KZ289065.1, KZ289064.1, KB469739.1, KB469741.2, JH792829.1, KV575236.1, KV575233.1, JH792826.1, KZ289071.1, JH792828.1, KZ289083.1, KB469740.1, KZ289087.1, KZ289089.1, JH792832.1, JH792833.1, JH792827.1, JH792834.1, JH792831.2, KB469742.1, KZ289067.1, KQ030484.1, KQ030494.1, KQ030496.1, KQ030497.1, KQ030492.1, KQ030493.2, KQ030491.1, KQ030488.1, KQ030489.1, KV575232.1, KV575241.1, KZ289076.1, KZ289068.1, KZ289069.1, KV575242.1, KZ289086.1, KZ289066.1, KK082441.1, KZ289077.1, KZ289078.1, KZ289079.1, KZ289073.1, KZ289074.1, KZ289075.1].                                                                                           at htsjdk.samtools.SAMSequenceDictionary.mergeDictionaries(SAMSequenceDictionary.java:322)                          at picard.sam.SamAlignmentMerger.getDictionaryForMergedBam(SamAlignmentMerger.java:197)                             at picard.sam.AbstractAlignmentMerger.mergeAlignment(AbstractAlignmentMerger.java:384)                              at picard.sam.SamAlignmentMerger.mergeAlignment(SamAlignmentMerger.java:181)                                        at picard.sam.MergeBamAlignment.doWork(MergeBamAlignment.java:366)                                                  at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:301)                                      at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)                                        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

**Comment by alecw** [comment] 2020-09-30 18:02
Hi @jurtlest ,

Are you sure that the reference fasta you used to create .dict is the same as the reference you used to create STAR index?  The problem is that in one of these, chromosome 1 is called "chr1" and in the other, it is called "1".  This is the case for 1-22, X,Y,MT.  STAR index and reference metadata created by Drop-seq tools need to agree on this.

Regards, Alec

**Comment by jurtlest** [comment] 2020-10-01 14:08
Hi Alec, 

Thank you for the prompt response. And thanks for pointing out the STAR index may be different. I am now in the process of recreating another index. But while I'm doing so, do you have an idea if Drop-seq or single cell seq preferrs primary assembly reference or no ??? Since I did not find such information in the manual or the dropseq protocol. 

Thanks!!!

**Comment by jamesnemesh** [comment] 2020-10-01 15:22
I think you should ask “What does your aligner of choice you use prefer”?  IE: What does STAR prefer? 	

Googling will drive you to many places, including STAR’s GitHub:
https://github.com/alexdobin/STAR/issues/479 <https://github.com/alexdobin/STAR/issues/479>

-Jim

**Comment by alecw** [comment] 2020-10-01 18:53
@jurtlest , it sounds like you have moved on from your original issue, so I'm going to close this issue.

**Closed by alecw** 2020-10-01 18:53 UTC
