### ISSUE TITLE
Patch to depend on newer biojava4

### ISSUE THREAD

**Issue by pgrt** [broadinstitute/Drop-seq#273] opened 2021-10-12 11:56 UTC
Hello,

I am working on the Debian packaging of Drop-seq.

In Debian we have the version 4.2.12 of biojava4, and some classes have been moved regarding version 4.0.0, on which Drop-seq is currently depending.

I would like to propose the enclosed patch, which changes the paths of some classes and allows to depend on biojava4 4.2.12. Maybe it could be useful to you if you upgrade this dependency version.

[biojava4_packages.txt](https://github.com/broadinstitute/Drop-seq/files/7329679/biojava4_packages.txt)

Best regards,

-- 
Pierre

**Comment by alecw** [comment] 2021-10-12 13:28
Hi Pierre,

Can you submit these changes as a pull request, including replacing lib/biojava-alignment-4.0.0.jar with the latest release?  This will cause the unit test suite to run so changes can be validated.  Also, I'd be inclined to upgrade to 5.4.0 rather than to a 3-year-old version. 

Regards, Alec

**Comment by jamesnemesh** [comment] 2023-08-02 13:56
These changes were merged into master, so the issue is no longer relevant.

**Closed as completed by jamesnemesh** 2023-08-02 13:56 UTC
